name: Nightly PRs to Main

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Nightly Submodule Update]
    types: [completed]

jobs:
  # Run the common workflow on each pull request
  Nightly_PR_to_Main:
    uses: 51Degrees/common-ci/.github/workflows/nightly-prs-to-main.yml@main
    with:
      repo-name: ${{ github.event.repository.name }}
      common-ci-ref: 9c01a09a46a53d4efc8f21d79c0c2b2ffcd2305b
    secrets:
      token: ${{ secrets.ACCESS_TOKEN }}
      TestResourceKey: ${{ secrets.SUPER_RESOURCE_KEY}}
